### ISSUE TITLE
find_all_dupes takes >1 day

### ISSUE THREAD

**Issue by zielmicha** [markfasheh/duperemove#122]
I'm trying to deduplicate about 2 TB of VM images backup (the images are mostly zeros). First hashing phase completes in about 2 hours, but then CPU-bound phase starts and hasn't ended yet.
"Hashing completed. Calculating duplicate extents - this may take some time."
First it has halted on 0% and then on about 40% and it's running for >24 hours. I've tried running both master (for few hours) and v0.10.

Is it expected? 
(From quick glance at the code, it looks like walk_dupe_hashes can be quadratic in worst case).

**Comment by zielmicha** [comment]
I've attached gdb to duperemove process and observed what it is doing (there are about 4 seconds between each "c" and ctrl-c):
https://gist.github.com/zielmicha/2e24aae754c2d09a48018431718108ef

**Comment by juliantaylor** [comment]
this step can take a lot of time, it may help to increase the blocksize, e.g. 1mb instead of 128kb. This helps a lot due to the non-linear time per block this step takes. If the images a mostly zero it should not harm the efficiency much.

**Comment by zielmicha** [comment]
Is this superlinear complexity necessary? If I understand btrfs API correctly it should be possible to perform deduplication in O(n) (when n is number of extents/bytes).

**Comment by zielmicha** [comment]
I don't understand duperemove logic.
Shouldn't something something like this work:
```
H = new hashtable of lists
for file in files:
  for extent in list_extents(file):
    H[hash(read extent data)].append((file, fe_logical, fe_physical))

for list in H.values:
  unique_extents = new hashtable
  for (file, fe_logical, fe_physical) in list:
    unique_extents[fe_physical] = (file, fe_logical)
  for item in unique_extents.values:
     invoke btrfs-shared-extent ioctl on (unique_extents.first, item) # we could move all operations on one file to one place (to avoid too many open syscalls) by using another hashtable
```
This is definitely linear, doesn't use btrees (which are probably slow than hashtables) and seems to be much simpler than what duperemove implements. Am I missing something?

(This approach doesn't deduplicate some blocks that should be when there are hash collisions, but with something like 128-bit murmur3 or even BLAKE that should be a problem)

**Comment by markfasheh** [comment]
Hi, thanks for looking at this. You are correct that find_all_dupes() is sub-optimal to say the least - giving us extremely poor worst-case performance due to a linear search through the duplicated blocks list. The easiest way to get that performance down is to fill one of the buckets up with most of your dupes, which your test case liikely does (as most blocks are zeros).

In my mind, we have two approaches to fixing the problem.

1) Make the algorithm better. Conceptually, this would be the best way to go. I will elaborate more on my efforts in this regard later.

2) Give an option to skip this step and essentially just dedupe the buckets one at a time. This would make more dedupe calls into the kernel of course but now that we've threaded that stage hopefully it wouldn't be so bad. The only added complexity I would have is that we try to pick the same file as dedupe target on each pass.


Btw, find_all_dupes() is entirely cpu-bound - it doesn't even allocate memory. I'm pretty sure you figured this out but I want to put it here so we're on the same page.

Regarding item 1) - I made a few passes in the past at improving our performance here (believe it or not, we were worse!). Initially it simply got cleaned up which gave us a ton of performance. After that, I tried to parallelize the algorithm by having different threads work on separate sections of the duplicated blocks space.

The biggest problem I ran into while parallelizing it is that any thread synchronization made performance worse. Mutexes were obviously out, but beyond that simple memory barriers didn't help either. Part of this was gcc (barriers were very expensive) and part of this is a fact of running in userspace where we can't reasonably get things like spinlocks going.


So if we want to go down path 1 (change the algorithm), your approach might make sense - basically I'm reading it as building the extents while we do the file scan, then finding duplicates from the extent list and deduping from those. Is that correct?

The downside I see is that we don't know ahead of time which extents would be duplicates so you'll wind up having to hash and store every possible extent which would be costly in terms of memory (or db io if we put them in a table). But maybe we could still do something during the hashing phase to make our find-extents phase faster.

Unfortunately I've been so slammed with other work lately that I haven't had a chance to look at anything like this in depth :(

**Comment by zielmicha** [comment]
I have created a prototype of this algorithm:
https://github.com/zielmicha/btrfs-dedup

Unfortunately it seems I have hit some kernel bug - after slamming kernel with millions of incorrect ioctl(BTRFS_IOC_FILE_EXTENT_SAME) it made one file permanently broken - BTRFS kernel thread hangs when I try to access it using show-shared-extents. I didn't have time to investigate it yet.

**Comment by markfasheh** [comment]
Hey would you be interested in trying the 'filewise-extent-search' branch I uploaded yesterday?

I made a test fs with just shy of a TB worth of mostly-zerod files (about 40% zeros). The extent search + remove-overlapping-extents code on that test took a far-too-long-to-measure time.

With commit 4ef3f40173a17071459b684fa8a19348aea6f271 I changed the code which finds overlapping extents to use an interval tree. This made the test finish in 10 hours. Not amazing, but far better than before. That commit is upstream.

The 'filewise-extent-search' branch has an additional commit that changes our core extent search. We no longer do the O(n^2) search across dupe buckets but instead do a linear walk, building a list of files to compare. Once we have that we can do the full compare of every file. We'll never compare any two files more than once and we'll never compare two files that don't share a block. That said, the file compare walk is still O(n^2) because in order to get as many possible dupes, we need to compare each file to every match.

With the code from commit aeacc0d8b875edc09ba91135dcd8eeb5eebc43b0 my test went from 10 hours to 2 hours. A much better result, though we can still get better.

I'm working on a couple things in this area. One idea is that we can optionally do a 'quick' compare where each file is only compared once. You would lose some dedupe but every file would still get at least one chance for comparison and the performance gain would potentially be significant. Lastly I think we can provide for some block-level deduping to just avoid the whole build-extents code. This would be a tradeoff of getting the most dedupe possible in the least search time but with the most dedupe requests.

**Comment by markfasheh** [comment]
We have a 'block dedupe' option now which is designed to skip the whole 'make extents' phase. In my tests of highly duplicated data it made a huge difference in total run time. If anyone is interested in testing that would be wonderful, otherwise I'll close this issue for now.
