### ISSUE TITLE
How stable is duperemove on xfs already?

### ISSUE THREAD

**Issue by brunoais** [markfasheh/duperemove#228]
From as much as I know, duperemove created xfs dedupe support back in 2017. I still see some indications of "experimental" in some places.
@markfasheh  Is xfs still experimental after 3/4 years?

**Comment by Artoria2e5** [comment]
A bit of renaming should be done in `btrfs-ioctl.h` now that all the ioctls used are no longer private to any single FS. `BTRFS_IOC_FILE_EXTENT_SAME` is now `FICLONERANGE`, and the correct way to test for support is just take any two files and watch for `EOPNOTSUPP` instead of the superblock stuff.

**Comment by lorddoskias** [comment]
There is nothing in duperemove which makes it more or less stable on one FS vs another. I've actually implemented the suggested changes by @Artoria2e5 in current master and duperemove now simply calls ioctl directly. But due to the fact that the VFS version of the code did retain the old codes it means it's backwards compatible. So even 0.11 should be able to dedupe if run on an XFS created with reflink support.

**Comment by Artoria2e5** [comment]
The new iofs actually has a value that is exaclty the same as the old btrfs thing. It's really just a new name.

**Comment by lorddoskias** [comment]
> The new iofs actually has a value that is exaclty the same as the old btrfs thing. It's really just a new name.

That's what I meant by the VFS code being backwards compatible. So I'm closing this issue as there isn't anything specific for duperemove to provide.
