### ISSUE TITLE
Document safety

### ISSUE THREAD

**Issue by aleksejrs** [markfasheh/duperemove#46]
What happens if a program tries to change one of the inodes?
What happens if the inodes are actually different when the kernel is told to dedupe them?
What happens if there is a bad block somewhere (no details, I was just told it could be a problem)?

**Comment by markfasheh** [comment]
Ok, so the first two seem like a reasonable "How safe is this?" question to put in the FAQ.

The answer is that the kernel internally is checking the data that is being dedupe, under lock. So barring a kernel bug, dedupe is safe from concurrent changes to the target inodes.

I'm not clear on what you mean by "What happens if there is a bad block somewhere (no details, I was just told it could be a problem)?"

But we could also have a "What are the downsides to dedupe?" question in the FAQ too. The most obvious are:

- possibility of increased fragmentation
- decreased duplication of data

**Comment by clobrother** [comment]
The FAQ is updated: https://github.com/markfasheh/duperemove/wiki/Frequently-Asked-Questions#is-duperemove-safe--can-it-break-my-data-
