### ISSUE TITLE
Production use?

### ISSUE THREAD

**Issue by Nefelim4ag** [markfasheh/duperemove#97]
Hi Mark, can you give a comment,
what you think, about duperemove and btrfs already ready for production?
//Use case: busy NFS file server, it's store Virtual Machine Images.

**Comment by lapsio** [comment]
Maybe not question to me, but I'm using btrfs with many features on maybe not super busy but publicly available server so more or less I had few issues related 24/7 I/O scenarios

I'd say duperemove for VMs may be bad idea (if they're actually being used directly from this storage. I've enabled btrfs lzo compression on VMs once and i had to delete them and copy again because it made VMs useless (boot MUCH longer than HDD even it was actually on SSD and basically guest system was not really responsive) so I'd say in case of duperemove it could also suffer from serious performance issues. But if it's just long term storage and VMs are not run directly from this storage, just kept as backup/archive - duperemove can save LOTS of space on VM images - it's probably most efficiently deduped content I've ever seen.

about btrfs itself:
Few times during server operation filesystem suddenly became read only because btrfs encountered some issue and decided to force remount drive in read only mode.

native btrfs RAID56 when finds damaged file will not fix it on the fly during first access, but return corrupted data and THEN fix it, so further access returns valid file - but first access when error detection occurs - nope - it's a bit annoying if you're generating checksums of files to track data integrity because many files can return invalid md5 hash during indexing, but when you'll check those files again they'll return actually valid md5 so it can result in ambiguous situations when you're not sure if index is invalid or just file got permanently corrupted.

scrub resume is buggy - it can be an issue on huge filesystems - especially huge RAID56 arrays (scrub performance on btrfs native RAID arrays is really poor, like 30MB/s). It turns out that sometimes scrub doesn't resume properly so in fact it won't scan whole storage but just part of it and then claim that everything is fine and checked.

However personally - I'd still recommend it because of noticeable disk space benefits due to native compression / duperemove, sufficient sequential access performence improvement both on plain single disk storage (prolly thanks to compression) and especially - on native RAID comparing to mdadm array. Also - I've been using btrfs with SSD dmcache and it works as expected as well.

**Comment by markfasheh** [comment]
lapsio, thank you for your comments.

As far as production usage, btrfs and duperemove are supported in SUSE Linux Enterprise Server so that should give you an idea of our confidence in the solution. We do pare down the feature set of btrfs to what we know works well however we are expanding that set with every update.

Re VMs, the tradeoff would be fragmentation of those VMs. So you would want to ask yourself whether the tradeoff makes sense in your particular situation.

**Comment by Nefelim4ag** [comment]
Thanks
